### ISSUE TITLE
Dont connect to myjdownloader

### ISSUE THREAD

**Issue by mericon** [OpenMediaVault-Plugin-Developers/openmediavault-jdownloader#7]
I entered the correct logindata but it still didnt connect.

**Comment by MaggiWuerze** [comment]
same problem here, file access is granted, credentials were entered but it wont appear in the webview

**Comment by cptjhmiller** [comment]
It can take a few minutes to properly startup, give it some time and keep refreshing the webpage.
You don't say there are any errors in the error box so i can't see what else it could be.

**Comment by kdo-razer** [comment]
Hello,

i installed this plugin on my pi2 in OMV. Also cannot connect to myjdownloader.  Unique-ID field says "awaiting first restart"... "Jdownloader-Info" and "Build Date" say "awaiting info"...

Any idea what my problem is ? Do i have to install some other software like java or so ?

Do i have to edit something in my router, port-forwardings for example ?

Thanks in advance,
Martin

**Comment by cptjhmiller** [comment]
If it says "awaiting first restart" you need to stop it then start it, ie restart.

**Comment by kdo-razer** [comment]
thx Miller... is restarting done by deactivating and reactivating the plugin, or do you prefer another way ?

BTW: after rebooting, there is a huge logfile, with at the end says:

```
----------------Request-------------------------
GET /JD/JDLastChanceRelPathBug.jar.enc HTTP/1.1
Host: cdn0.appwork.org
Accept-Language: en
User-Agent: AppWork .jd_home
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Pragma: no-cache
Cache-Control: no-cache, no-store
Connection: Close
----------------Response Information------------
Connection-Time: 30ms
----------------Response------------------------
HTTP/1.1 200 OK
Server: nginx/1.11.3
Date: Sun, 06 Nov 2016 12:45:04 GMT
Content-Type: application/octet-stream
Content-Length: 2176
Last-Modified: Mon, 15 Feb 2016 18:46:12 GMT
Connection: close
ETag: "56c21cf4-880"
Accept-Ranges: bytes
------------------------------------------------

Try to replace: client
java.lang.NoSuchFieldException: replacerListSortedOnKeyLength
    at java.lang.Class.getDeclaredField(Class.java:1961)
    at org.jdownloader.update.lastchance.SetListToDefaultPathBuilderLastChance.runInternal(SetListToDefaultPathBuilderLastChance.java:26)
    at org.appwork.updatesys.client.lastchance.LastChanceUtils.runInternal(LastChanceUtils.java:163)
    at org.jdownloader.update.lastchance.LastChanceManager.internalRun(LastChanceManager.java:190)
    at org.jdownloader.update.lastchance.LastChanceManager.run(LastChanceManager.java:114)
    at org.jdownloader.update.launcher.SecondLevelLauncher$2.run(SecondLevelLauncher.java:283)
Try to replace: selfUpdateClient
java.lang.NoSuchFieldException: replacerListSortedOnKeyLength
    at java.lang.Class.getDeclaredField(Class.java:1961)
    at org.jdownloader.update.lastchance.SetListToDefaultPathBuilderLastChance.runInternal(SetListToDefaultPathBuilderLastChance.java:26)
    at org.appwork.updatesys.client.lastchance.LastChanceUtils.runInternal(LastChanceUtils.java:163)
    at org.jdownloader.update.lastchance.LastChanceManager.internalRun(LastChanceManager.java:190)
    at org.jdownloader.update.lastchance.LastChanceManager.run(LastChanceManager.java:114)
    at org.jdownloader.update.launcher.SecondLevelLauncher$2.run(SecondLevelLauncher.java:283)

```

Sounds like an error message... any idea what i could do ?

**Comment by cptjhmiller** [comment]
I would just un-enable save/apply then enable save/apply

What does it now say on the plugin page?

**Comment by kdo-razer** [comment]
first thank you for helping me... I can disable/enable the plugin as often as i want, it never gets connected... jdownloader-service is running, but no connection is established... Here´s the complete log after a complete restart.

[jdownloader.txt](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-jdownloader/files/573884/jdownloader.txt)

Searched the internet on my owm the last hours. Reinstalled java, did all updates, but still no connection.

I even reinstalled the plugin, with any success...

**Comment by cptjhmiller** [comment]
If you have team viewer I can take a closer look if you wish?

**Comment by kdo-razer** [comment]
i really wish ;) How can we connect to each other ?

**Comment by cptjhmiller** [comment]
https://www.teamviewer.com/en/download/windows/
download and run TV, it will show userID and a password/passcode give this info to me and it will allow me to see your PC and if permission is given, take control.

**Comment by kdo-razer** [comment]
already installed... shouldn´t i pm the ID and passwort to you instead of posting them here ?

**Comment by cptjhmiller** [comment]
yes only i can see it then

**Comment by kdo-razer** [comment]
278 125 789

6447


thx !!


Am 06.11.2016 um 16:25 schrieb Jamie:

**Comment by kdo-razer** [comment]
Jamie - updater has finished... time for reconnecting ?

**Comment by cptjhmiller** [comment]
OK

**Comment by kdo-razer** [comment]
278 125 789 / 6447

**Comment by EletroLaix** [comment]
Hi, I have the same problem with Banana Pro, I installed the plugin but does not connect, I tried restarting but nothing.
Have you found a solution?
